// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_treasure_hunter = "CgkI967U96ofEAIQBg"; // <GPGSID>
        public const string achievement_that_belongs_in_my_pocket = "CgkI967U96ofEAIQBA"; // <GPGSID>
        public const string achievement_hoarder_of_gems = "CgkI967U96ofEAIQBQ"; // <GPGSID>
        public const string leaderboard_top_times = "CgkI967U96ofEAIQAw"; // <GPGSID>
        public const string achievement_jungling_around = "CgkI967U96ofEAIQBw"; // <GPGSID>
        public const string achievement_wood_you_kindly_stop_that = "CgkI967U96ofEAIQCA"; // <GPGSID>
        public const string achievement_lucky_me = "CgkI967U96ofEAIQAg"; // <GPGSID>
        public const string achievement_newfound_friendship = "CgkI967U96ofEAIQCQ"; // <GPGSID>
        public const string achievement_that_was_easy = "CgkI967U96ofEAIQAQ"; // <GPGSID>

}

